apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prom-pvc.yaml
  - prom-configmap.yaml
  - prom-deployment.yaml
  - prom-service.yaml
  - graf-pvc.yaml
  - graf-deployment.yaml
  - graf-service.yaml