apiVersion: apps/v1
kind: Deployment
metadata: 
  name: prom-pod
  labels:
    env: prom-env
spec:
  replicas: 2
  selector:
    matchLabels:
      env: prom-env
  template:
    metadata:
      name: prom-pod
      labels: 
        env: prom-env
    spec:
      containers:
      - name: prom-pod
        image: khushi09/prometheus:latest
        args: 
        - "--config.file=prometheus-2.18.1.linux-amd64/prometheus.yml"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-persistent-storage
          mountPath: prometheus-2.18.1.linux-amd64/data
        - name: prometheus-config-volume
          mountPath: prometheus-2.18.1.linux-amd64/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: prometheus-persistent-storage
        persistentVolumeClaim:
          claimName: prom-pvc 
      - name: prometheus-config-volume
        configMap:
          name: prom-config